/**
 * VPS Docker deployment file generator for StanNG v2.
 * Generates docker-compose.yml, nginx.conf, .env, and deploy.sh
 * so the user can deploy StanNG on any VPS with Docker.
 */

export interface VpsDeployConfig {
  name: string
  uuid: string
  adminPassword?: string
  domain?: string
  port?: string
}

export function generateDockerCompose(cfg: VpsDeployConfig): string {
  const port = cfg.port || '8080'
  return `# miliconfig — StanNG v2 Docker Deployment
# Generated by miliconfigpro panel

services:
  stanng:
    image: python:3.12-slim
    container_name: ${cfg.name || 'stanng'}
    restart: unless-stopped
    working_dir: /app
    command: >
      sh -c "pip install -r requirements.txt --quiet &&
             python main.py"
    environment:
      - ADMIN_PASSWORD=${cfg.adminPassword || 'changeme'}
      - SECRET_KEY=${cfg.uuid}
      - PORT=${port}
      - PUBLIC_DOMAIN=${cfg.domain || ''}
    volumes:
      - ./stanng-data:/app/data
      - ./stanng-src:/app
    ports:
      - "${port}:${port}"
    healthcheck:
      test: ["CMD", "python", "-c", "import httpx; httpx.get('http://localhost:${port}/login')"]
      interval: 30s
      timeout: 10s
      retries: 3

  nginx:
    image: nginx:alpine
    container_name: ${cfg.name || 'stanng'}-nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./certbot/conf:/etc/letsencrypt:ro
      - ./certbot/www:/var/www/certbot:ro
    depends_on:
      - stanng
    command: "/bin/sh -c 'while :; do sleep 6h & wait \${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"

  certbot:
    image: certbot/certbot
    container_name: ${cfg.name || 'stanng'}-certbot
    volumes:
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait \${!}; done;'"
    profiles:
      - certonly
`
}

export function generateNginxConf(cfg: VpsDeployConfig): string {
  const domain = cfg.domain || '_'
  return `# miliconfig — StanNG nginx reverse proxy
events {
    worker_connections 1024;
}

http {
    upstream stanng {
        server stanng:${cfg.port || '8080'};
    }

    server {
        listen 80;
        server_name ${domain};

        location /.well-known/acme-challenge/ {
            root /var/www/certbot;
        }

        location / {
            proxy_pass http://stanng;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;

            # WebSocket support (required for VLESS)
            proxy_http_version 1.1;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection "upgrade";
            proxy_read_timeout 86400;
        }
    }

    # HTTPS server (uncomment after first certbot run)
    # server {
    #     listen 443 ssl http2;
    #     server_name ${domain};
    #
    #     ssl_certificate /etc/letsencrypt/live/${domain}/fullchain.pem;
    #     ssl_certificate_key /etc/letsencrypt/live/${domain}/privkey.pem;
    #
    #     location / {
    #         proxy_pass http://stanng;
    #         proxy_set_header Host $host;
    #         proxy_set_header X-Real-IP $remote_addr;
    #         proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    #         proxy_set_header X-Forwarded-Proto $scheme;
    #         proxy_http_version 1.1;
    #         proxy_set_header Upgrade $http_upgrade;
    #         proxy_set_header Connection "upgrade";
    #         proxy_read_timeout 86400;
    #     }
    # }
}
`
}

export function generateEnvFile(cfg: VpsDeployConfig): string {
  return `# miliconfig — StanNG v2 environment
ADMIN_PASSWORD=${cfg.adminPassword || 'changeme'}
SECRET_KEY=${cfg.uuid}
PORT=${cfg.port || '8080'}
PUBLIC_DOMAIN=${cfg.domain || ''}
`
}

export function generateDeployScript(cfg: VpsDeployConfig): string {
  return `#!/bin/bash
# miliconfig — StanNG v2 one-click deploy
# Run this on your VPS: bash deploy.sh

set -e

echo "🚀 Deploying StanNG v2..."
echo ""

# 1. Create directories
mkdir -p stanng-src stanng-data certbot/conf certbot/www

# 2. Clone StanNG source
echo "📥 Cloning StanNG source..."
rm -rf stanng-src/*
git clone --depth 1 https://github.com/youdidking/stanngv2.git stanng-src

# 3. Start services
echo "🐳 Starting Docker containers..."
docker compose up -d

echo ""
echo "✅ StanNG is running!"
echo "   HTTP: http://YOUR_SERVER_IP:${cfg.port || '8080'}"
echo "   Panel: http://YOUR_SERVER_IP:${cfg.port || '8080'}/login"
echo "   Password: ${cfg.adminPassword || 'changeme'}"
echo ""
echo "To set up HTTPS:"
echo "  1. Point your domain DNS to this server"
echo "  2. Edit .env and set PUBLIC_DOMAIN=your.domain.com"
echo "  3. Run: docker compose --profile certonly run --rm certbot certonly --webroot -w /var/www/certbot -d your.domain.com"
echo "  4. Uncomment the HTTPS server block in nginx.conf"
echo "  5. Run: docker compose restart nginx"
`
}
