/**
 * VPS Docker deployment file generator for StanNG v2.
 * Generates docker-compose.yml, nginx.conf, .env, and deploy.sh
 * so the user can deploy StanNG on any VPS with Docker.
 */

export interface VpsDeployConfig {
  name: string
  uuid: string
  adminPassword?: string
  domain?: string
  port?: string
}

export function generateDockerCompose(cfg: VpsDeployConfig): string {
  const port = cfg.port || '8080'
  return `# miliconfig — StanNG v2 Docker Deployment
# Generated by miliconfigpro panel

services:
  stanng:
    image: python:3.12-slim
    container_name: ${cfg.name || 'stanng'}
    restart: unless-stopped
    working_dir: /app
    command: >
      sh -c "pip install -r requirements.txt --quiet &&
             python main.py"
    environment:
      - ADMIN_PASSWORD=${cfg.adminPassword || 'changeme'}
      - SECRET_KEY=${cfg.uuid}
      - PORT=${port}
      - PUBLIC_DOMAIN=${cfg.domain || ''}
    volumes:
      - ./stanng-data:/app/data
      - ./stanng-src:/app
    ports:
      - "${port}:${port}"
    healthcheck:
      test: ["CMD", "python", "-c", "import httpx; httpx.get('http://localhost:${port}/login')"]
      interval: 30s
      timeout: 10s
      retries: 3

  nginx:
    image: nginx:alpine
    container_name: ${cfg.name || 'stanng'}-nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./certbot/conf:/etc/letsencrypt:ro
      - ./certbot/www:/var/www/certbot:ro
    depends_on:
      - stanng
    command: "/bin/sh -c 'while :; do sleep 6h & wait \${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"

  certbot:
    image: certbot/certbot
    container_name: ${cfg.name || 'stanng'}-certbot
    volumes:
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait \${!}; done;'"
    profiles:
      - certonly
`
}

export function generateNginxConf(cfg: VpsDeployConfig): string {
  const domain = cfg.domain || '_'
  return `# miliconfig — StanNG nginx reverse proxy
events {
    worker_connections 1024;
}

http {
    upstream stanng {
        server stanng:${cfg.port || '8080'};
    }

    server {
        listen 80;
        server_name ${domain};

        location /.well-known/acme-challenge/ {
            root /var/www/certbot;
        }

        location / {
            proxy_pass http://stanng;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;

            # WebSocket support (required for VLESS)
            proxy_http_version 1.1;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection "upgrade";
            proxy_read_timeout 86400;
        }
    }

    # HTTPS server (uncomment after first certbot run)
    # server {
    #     listen 443 ssl http2;
    #     server_name ${domain};
    #
    #     ssl_certificate /etc/letsencrypt/live/${domain}/fullchain.pem;
    #     ssl_certificate_key /etc/letsencrypt/live/${domain}/privkey.pem;
    #
    #     location / {
    #         proxy_pass http://stanng;
    #         proxy_set_header Host $host;
    #         proxy_set_header X-Real-IP $remote_addr;
    #         proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    #         proxy_set_header X-Forwarded-Proto $scheme;
    #         proxy_http_version 1.1;
    #         proxy_set_header Upgrade $http_upgrade;
    #         proxy_set_header Connection "upgrade";
    #         proxy_read_timeout 86400;
    #     }
    # }
}
`
}

export function generateEnvFile(cfg: VpsDeployConfig): string {
  return `# miliconfig — StanNG v2 environment
ADMIN_PASSWORD=${cfg.adminPassword || 'changeme'}
SECRET_KEY=${cfg.uuid}
PORT=${cfg.port || '8080'}
PUBLIC_DOMAIN=${cfg.domain || ''}
`
}

// ── Railway deployment ────────────────────────────────────────────────────────

export function generateRailwayDockerfile(cfg: VpsDeployConfig): string {
  const pw = cfg.adminPassword || cfg.uuid || 'changeme'
  return `# miliconfig — StanNG v2 Railway Deployment
# Single container with xray-core + Python FastAPI
FROM debian:bookworm-slim

RUN apt-get update && apt-get install -y --no-install-recommends \\\n      curl unzip python3 python3-pip python3-venv \\\n      && rm -rf /var/lib/apt/lists/*

# Install xray-core
RUN ARCH=$(uname -m) && \\\n      if [ "$ARCH" = "x86_64" ]; then XRAY_ARCH="64"; \\\n      elif [ "$ARCH" = "aarch64" ]; then XRAY_ARCH="arm64-v8a"; \\\n      elif [ "$ARCH" = "armv7l" ]; then XRAY_ARCH="arm32-v7a"; \\\n      else XRAY_ARCH="64"; fi && \\\n      curl -fsSL "https://github.com/XTLS/Xray-core/releases/latest/download/Xray-linux-$XRAY_ARCH.zip" \\\n        -o /tmp/xray.zip && \\\n      unzip -o /tmp/xray.zip -d /usr/local/bin/ && \\\n      chmod +x /usr/local/bin/xray && \\\n      rm /tmp/xray.zip

WORKDIR /app

# Clone StanNG source
RUN git clone --depth 1 https://github.com/youdidking/stanngv2.git /app

# Install Python dependencies
RUN pip install --no-cache-dir --break-system-packages -r requirements.txt

# Persist data across restarts
RUN mkdir -p /app/data

ENV ADMIN_PASSWORD=${pw}
ENV SECRET_KEY=${cfg.uuid}
ENV PORT=8080
ENV PUBLIC_DOMAIN=${cfg.domain || ''}

EXPOSE 8080

CMD ["sh", "-c", "python main.py"]`
}

export function generateRailwayToml(cfg: VpsDeployConfig): string {
  const pw = cfg.adminPassword || cfg.uuid || 'changeme'
  return `# miliconfig — Railway deploy config for StanNG v2
# Generated by miliconfigpro panel

[build]
dockerfilePath = "Dockerfile"

[deploy]
startCommand = "python main.py"
healthcheckPath = "/login"
healthcheckTimeout = 30
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 5

[deploy.env]
ADMIN_PASSWORD = "${pw}"
SECRET_KEY = "${cfg.uuid}"
PORT = "8080"
PUBLIC_DOMAIN = "${cfg.domain || ''}"
`
}

export function generateRailwayReadme(cfg: VpsDeployConfig): string {
  const pw = cfg.adminPassword || cfg.uuid || 'changeme'
  return `# ${cfg.name} — StanNG v2 Railway Deployment
\n## One-Click Deploy\n\n1. Fork https://github.com/youdidking/stanngv2 to your GitHub\n2. Go to https://railway.app/new\n3. Click **Deploy from GitHub repo** → select the forked repo\n4. Railway auto-detects the Dockerfile and deploys\n5. In **Settings → Variables**, set:\n\n   | Variable | Value |
   |----------|-------|
   | ADMIN_PASSWORD | \`${pw}\` |
   | SECRET_KEY | \`${cfg.uuid}\` |
   | PORT | \`8080\` |
\n6. In **Settings → Networking**, click **Generate Domain**\n\n## Panel Access\n\n- URL: https://your-app.up.railway.app/login\n- Password: \`${pw}\`\n\n## Files in This Package\n\n| File | Purpose |
|------|--------|
| Dockerfile | Builds StanNG with xray-core + Python |
| railway.toml | Railway deploy configuration |

---\nGenerated by miliconfigpro panel\n`
}

export function generateDeployScript(cfg: VpsDeployConfig): string {
  return `#!/bin/bash
# miliconfig — StanNG v2 one-click deploy
# Run this on your VPS: bash deploy.sh

set -e

echo "🚀 Deploying StanNG v2..."
echo ""

# 1. Create directories
mkdir -p stanng-src stanng-data certbot/conf certbot/www

# 2. Clone StanNG source
echo "📥 Cloning StanNG source..."
rm -rf stanng-src/*
git clone --depth 1 https://github.com/youdidking/stanngv2.git stanng-src

# 3. Start services
echo "🐳 Starting Docker containers..."
docker compose up -d

echo ""
echo "✅ StanNG is running!"
echo "   HTTP: http://YOUR_SERVER_IP:${cfg.port || '8080'}"
echo "   Panel: http://YOUR_SERVER_IP:${cfg.port || '8080'}/login"
echo "   Password: ${cfg.adminPassword || 'changeme'}"
echo ""
echo "To set up HTTPS:"
echo "  1. Point your domain DNS to this server"
echo "  2. Edit .env and set PUBLIC_DOMAIN=your.domain.com"
echo "  3. Run: docker compose --profile certonly run --rm certbot certonly --webroot -w /var/www/certbot -d your.domain.com"
echo "  4. Uncomment the HTTPS server block in nginx.conf"
echo "  5. Run: docker compose restart nginx"
`
}
