/**
 * VPS / Railway Docker deployment file generators.
 *
 * Everything is driven by the shared panel catalog (shared/panels.ts), so any
 * catalog panel — a plain Python app (StanNG v2 / PXPANEL), a published
 * container image (3X-UI / S-UI / PasarGuard / Remnawave) — produces a working
 * docker-compose bundle from the same template. Panels that need PostgreSQL or
 * Redis get those sidecars generated automatically.
 */

import type { PanelSpec } from '../../shared/panels'
import { PANEL_ORIGIN, panelRepoUrl } from '../../shared/panels'

export interface VpsDeployConfig {
  name: string
  uuid: string
  adminPassword?: string
  domain?: string
  port?: string
  panel: PanelSpec
}

function panelPort(cfg: VpsDeployConfig): number {
  const configured = Number(cfg.port)
  return Number.isFinite(configured) && configured > 0 ? configured : cfg.panel.port
}

const DB_USER = 'panel'
const DB_NAME = 'panel'

/** Sidecar (PostgreSQL / Redis) env vars the panel understands. */
function sidecarEnv(cfg: VpsDeployConfig): Array<[string, string]> {
  const panel = cfg.panel
  const env: Array<[string, string]> = []
  if (panel.requiresDb === 'postgres' && panel.env.dbUrl) {
    env.push([panel.env.dbUrl, `postgresql://${DB_USER}:${cfg.uuid}@db:5432/${DB_NAME}`])
  }
  if (panel.requiresRedis) {
    if (panel.env.redisHost) env.push([panel.env.redisHost, 'redis'])
    if (panel.env.redisUrl) env.push([panel.env.redisUrl, 'redis://redis:6379/0'])
  }
  return env
}

/** Env vars the panel understands, as key/value pairs (secrets included). */
function panelEnv(cfg: VpsDeployConfig): Array<[string, string]> {
  const panel = cfg.panel
  const env: Array<[string, string]> = []
  if (panel.env.adminPassword) env.push([panel.env.adminPassword, cfg.adminPassword || cfg.uuid])
  if (panel.env.secretKey) env.push([panel.env.secretKey, cfg.uuid])
  if (panel.env.port) env.push([panel.env.port, String(panelPort(cfg))])
  if (panel.env.dataDir) env.push([panel.env.dataDir, '/data'])
  if (panel.env.publicDomain) env.push([panel.env.publicDomain, cfg.domain || ''])
  env.push(...sidecarEnv(cfg))
  return env
}

/**
 * A single-image Dockerfile that clones and runs a Python-based panel.
 * Returns an empty string for panels that ship a published image (their compose
 * uses `image:` directly, so there is nothing to build locally).
 */
export function generateDockerfile(cfg: VpsDeployConfig): string {
  const panel = cfg.panel
  if (panel.dockerImage) return ''
  const port = panelPort(cfg)
  const start = panel.startCommand ?? 'python main.py'

  const lines: string[] = [
    `# miliconfig — ${panel.name} deployment`,
    '# Generated by miliconfigpro panel',
    'FROM debian:bookworm-slim',
    '',
    'RUN apt-get update && apt-get install -y --no-install-recommends \\\\',
    '      curl unzip git ca-certificates python3 python3-pip python3-venv \\\\',
    '      && rm -rf /var/lib/apt/lists/*',
  ]

  if (panel.needsXray) {
    lines.push(
      '',
      '# Install xray-core (proxy panel)',
      'RUN ARCH="$(uname -m)" \\\\',
      '      && case "$ARCH" in x86_64) XRAY_ARCH=64 ;; aarch64) XRAY_ARCH=arm64-v8a ;; armv7l) XRAY_ARCH=arm32-v7a ;; *) XRAY_ARCH=64 ;; esac \\\\',
      '      && curl -fsSL "https://github.com/XTLS/Xray-core/releases/latest/download/Xray-linux-$XRAY_ARCH.zip" -o /tmp/xray.zip \\\\',
      '      && unzip -o /tmp/xray.zip -d /usr/local/bin/ \\\\',
      '      && chmod +x /usr/local/bin/xray \\\\',
      '      && rm /tmp/xray.zip',
    )
  }

  lines.push(
    'WORKDIR /app',
    '',
    `# Clone the ${panel.name} source (${panel.repo})`,
    `RUN git clone --depth 1 ${panelRepoUrl(panel)} /app`,
    '',
    '# Install Python dependencies',
    'RUN pip install --no-cache-dir --break-system-packages -r requirements.txt',
    '',
    'RUN mkdir -p /app/data',
    '',
  )
  for (const [k, v] of panelEnv(cfg)) lines.push(`ENV ${k}=${v}`)
  lines.push('', `EXPOSE ${port}`, '', `CMD ["sh", "-c", "${start}"]`, '')

  return lines.join('\n')
}

/** Compose fragment for the PostgreSQL sidecar, when the panel needs one. */
function postgresService(cfg: VpsDeployConfig): string {
  return `
  db:
    image: postgres:16-alpine
    container_name: ${cfg.name}-db
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${cfg.uuid}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - ./db-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}"]
      interval: 10s
      timeout: 5s
      retries: 10
`
}

/** Compose fragment for the Redis sidecar, when the panel needs one. */
function redisService(cfg: VpsDeployConfig): string {
  return `
  redis:
    image: redis:7-alpine
    container_name: ${cfg.name}-redis
    restart: unless-stopped
    command: ["redis-server", "--appendonly", "yes"]
    volumes:
      - ./redis-data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 10
`
}

export function generateDockerCompose(cfg: VpsDeployConfig): string {
  const panel = cfg.panel
  const port = panelPort(cfg)
  const svc = cfg.name || panel.id
  const ports = [port, ...(panel.extraPorts ?? [])]
  const dataPath = panel.dataVolume ?? '/data'
  const depends = [
    ...(panel.requiresDb === 'postgres' ? ['db'] : []),
    ...(panel.requiresRedis ? ['redis'] : []),
  ]

  const app: string[] = [
    `  panel:`,
    panel.dockerImage
      ? `    image: ${panel.dockerImage}`
      : `    build: .\n    image: ${svc}:latest`,
  ]
  if (panel.dockerImage && panel.hasDockerfile) {
    app.push(
      `    # جایگزین: ساخت از سورس مخزن (اگر تصویر آماده در دسترس نبود)`,
      `    # build:`,
      `    #   context: ${panelRepoUrl(panel)}`,
    )
  }
  app.push(
    `    container_name: ${svc}`,
    `    restart: unless-stopped`,
    ...(panel.tty ? [`    tty: true`] : []),
    ...(panel.capAdd?.length ? [`    cap_add:`, ...panel.capAdd.map((c) => `      - ${c}`)] : []),
    ...(panel.sysctls?.length ? [`    sysctls:`, ...panel.sysctls.map((s) => `      - ${s}`)] : []),
    `    env_file: .env`,
    ...(depends.length ? [`    depends_on:`, ...depends.map((d) => `      - ${d}`)] : []),
    `    volumes:`,
    `      - ./panel-data:${dataPath}`,
    ...(panel.extraVolumes ?? []).map((v) => `      - ${v}`),
    `    ports:`,
    ...ports.map((p) => `      - "${p}:${p}"`),
    ...(panel.udpPorts ?? []).map((p) => `      - "${p}:${p}/udp"`),
  )
  if (!panel.dockerImage) {
    app.push(
      `    healthcheck:`,
      `      test: ["CMD", "python3", "-c", "import urllib.request; urllib.request.urlopen('http://localhost:${port}${panel.panelPath}')"]`,
      `      interval: 30s`,
      `      timeout: 10s`,
      `      retries: 3`,
    )
  }

  const header = [
    `# miliconfig — ${panel.name} deployment`,
    `# ${panel.repo} · ${panel.origin ? PANEL_ORIGIN[panel.origin].label : ''}`.trim(),
    panel.notes ? `# ${panel.notes}` : '',
    `# Generated by miliconfigpro panel`,
    '',
    'services:',
    app.join('\n'),
  ].filter((l) => l !== '')

  const sidecars = [
    ...(panel.requiresDb === 'postgres' ? [postgresService(cfg)] : []),
    ...(panel.requiresRedis ? [redisService(cfg)] : []),
  ]

  // The panel itself may already publish 443 (proxy panels) — nginx must not
  // claim the same host port, otherwise `docker compose up` fails.
  const nginxPorts = [80, ...(ports.includes(443) ? [] : [443])]

  const tail = `
  nginx:
    image: nginx:alpine
    container_name: ${svc}-nginx
    restart: unless-stopped
    ports:
${nginxPorts.map((p) => `      - "${p}:${p}"`).join('\n')}
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./certbot/conf:/etc/letsencrypt:ro
      - ./certbot/www:/var/www/certbot:ro
    depends_on:
      - panel
    command: >-
      /bin/sh -c 'while :; do sleep 6h; nginx -s reload; done & nginx -g "daemon off;"'

  certbot:
    image: certbot/certbot
    container_name: ${svc}-certbot
    volumes:
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    entrypoint: >-
      /bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h; done'
    profiles:
      - certonly
`

  return header.join('\n') + sidecars.join('') + tail
}

export function generateNginxConf(cfg: VpsDeployConfig): string {
  const domain = cfg.domain || '_'
  const port = panelPort(cfg)
  return `# miliconfig — ${cfg.panel.name} nginx reverse proxy
events {
    worker_connections 1024;
}

http {
    upstream panel {
        server panel:${port};
    }

    server {
        listen 80;
        server_name ${domain};

        location /.well-known/acme-challenge/ {
            root /var/www/certbot;
        }

        location / {
            proxy_pass http://panel;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;

            # WebSocket support (required for VLESS)
            proxy_http_version 1.1;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection "upgrade";
            proxy_read_timeout 86400;
        }
    }

    # HTTPS server (uncomment after first certbot run)
    # server {
    #     listen 443 ssl http2;
    #     server_name ${domain};
    #
    #     ssl_certificate /etc/letsencrypt/live/${domain}/fullchain.pem;
    #     ssl_certificate_key /etc/letsencrypt/live/${domain}/privkey.pem;
    #
    #     location / {
    #         proxy_pass http://panel;
    #         proxy_set_header Host $host;
    #         proxy_set_header X-Real-IP $remote_addr;
    #         proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    #         proxy_set_header X-Forwarded-Proto $scheme;
    #         proxy_http_version 1.1;
    #         proxy_set_header Upgrade $http_upgrade;
    #         proxy_set_header Connection "upgrade";
    #         proxy_read_timeout 86400;
    #     }
    # }
}
`
}

export function generateEnvFile(cfg: VpsDeployConfig): string {
  const lines = [`# miliconfig — ${cfg.panel.name} environment`]
  for (const [k, v] of panelEnv(cfg)) lines.push(`${k}=${v}`)
  return lines.join('\n') + '\n'
}

/** README shipped inside the VPS ZIP, with the panel's real requirements. */
export function generateVpsReadme(cfg: VpsDeployConfig, zipName: string): string {
  const panel = cfg.panel
  const port = panelPort(cfg)
  const pw = cfg.adminPassword || cfg.uuid
  const origin = panel.origin ? PANEL_ORIGIN[panel.origin] : undefined
  return `# ${cfg.name} — ${panel.name} (Docker VPS)

منبع: ${panel.url}${origin ? ` · ${origin.flag} ${origin.label}` : ''}
آخرین کامیت بررسی‌شده: ${panel.lastCommit ?? '—'} · بررسی: ${panel.verifiedAt ?? '—'}

## نصب سریع

\`\`\`bash
unzip ${zipName}
cd ${cfg.name}
bash deploy.sh
\`\`\`

## دسترسی

- پنل: \`http://YOUR_SERVER_IP:${port}${panel.panelPath}\`
- رمز پیش‌فرض (اگر پنل از ADMIN_PASSWORD پشتیبانی کند): \`${pw}\`
${panel.defaultAdminPassword ? `- ورود پیش‌فرض خود پنل: \`admin\` / \`${panel.defaultAdminPassword}\`\n` : ''}
## پیش‌نیازها

${panel.notes ?? 'بدون نیاز خاصی.'}
${panel.requiresDb === 'postgres' ? '\n> PostgreSQL به‌صورت سرویس `db` در compose ساخته می‌شود و رمز آن همان UUID این استقرار است.\n' : ''}${panel.requiresRedis ? '> Redis به‌صورت سرویس `redis` در compose ساخته می‌شود.\n' : ''}
## فایل‌های این بسته

| فایل | کاربرد |
|------|--------|
| docker-compose.yml | سرویس پنل${panel.requiresDb ? ' + دیتابیس' : ''}${panel.requiresRedis ? ' + Redis' : ''} + nginx |
| .env | متغیرهای محیطی پنل |
| nginx.conf | ریورس‌پروکسی و وب‌سوکت |
| deploy.sh | اجرای یک‌مرحله‌ای روی VPS |
${panel.dockerImage ? '' : '| Dockerfile | ساخت ایمیج از سورس پنل |\n'}
---
Generated by miliconfigpro panel
`
}

// ── Railway deployment ────────────────────────────────────────────────────────

export function generateRailwayDockerfile(cfg: VpsDeployConfig): string {
  return generateDockerfile(cfg)
}

export function generateRailwayToml(cfg: VpsDeployConfig): string {
  const panel = cfg.panel
  const start = panel.startCommand ?? 'python main.py'
  const envLines = panelEnv(cfg).map(([k, v]) => `${k} = "${v}"`).join('\n')
  return `# miliconfig — Railway deploy config for ${panel.name}
# Generated by miliconfigpro panel

[build]
dockerfilePath = "Dockerfile"

[deploy]
startCommand = "${start}"
healthcheckPath = "${panel.healthPath ?? panel.panelPath}"
healthcheckTimeout = 30
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 5

[deploy.env]
${envLines}
`
}

export function generateRailwayReadme(cfg: VpsDeployConfig): string {
  const panel = cfg.panel
  const pw = cfg.adminPassword || cfg.uuid || 'changeme'
  return `# ${cfg.name} — ${panel.name} Railway Deployment

## One-Click Deploy

1. Fork ${panel.url} to your GitHub
2. Go to https://railway.app/new
3. Click **Deploy from GitHub repo** → select the forked repo
4. Railway auto-detects the Dockerfile and deploys
5. In **Settings → Variables**, set:

   | Variable | Value |
   |----------|-------|
   | ADMIN_PASSWORD | \`${pw}\` |
   | SECRET_KEY | \`${cfg.uuid}\` |
   | PORT | \`${panel.port}\` |

6. In **Settings → Networking**, click **Generate Domain**

## Panel Access

- URL: https://your-app.up.railway.app${panel.panelPath}
- Password: \`${pw}\`

## Files in This Package

| File | Purpose |
|------|---------|
| Dockerfile | Builds ${panel.name} |
| railway.toml | Railway deploy configuration |

---
Generated by miliconfigpro panel
`
}

export function generateDeployScript(cfg: VpsDeployConfig): string {
  const panel = cfg.panel
  const port = panelPort(cfg)
  const pw = cfg.adminPassword || 'changeme'
  return `#!/bin/bash
# miliconfig — ${panel.name} one-click deploy
# Run this on your VPS: bash deploy.sh

set -e

echo "🚀 Deploying ${panel.name}..."

# 1. Create directories
mkdir -p panel-data certbot/conf certbot/www${panel.requiresDb === 'postgres' ? ' db-data' : ''}${panel.requiresRedis ? ' redis-data' : ''}

# 2. Build and start services
echo "🐳 Building and starting Docker containers..."
docker compose up -d --build

echo ""
echo "✅ ${panel.name} is running!"
echo "   HTTP:  http://YOUR_SERVER_IP:${port}"
echo "   Panel: http://YOUR_SERVER_IP:${port}${panel.panelPath}"
${panel.defaultAdminPassword ? `echo "   Default login: admin / ${panel.defaultAdminPassword}"\n` : ''}echo "   Password: ${pw}"
${panel.requiresDb === 'postgres' ? 'echo "   DB:    PostgreSQL sidecar (user: panel, db: panel)"\n' : ''}${panel.requiresRedis ? 'echo "   Cache: Redis sidecar"\n' : ''}echo ""
echo "To set up HTTPS:"
echo "  1. Point your domain DNS to this server"
echo "  2. Edit .env and set PUBLIC_DOMAIN=your.domain.com"
echo "  3. Run: docker compose --profile certonly run --rm certbot certonly --webroot -w /var/www/certbot -d your.domain.com"
echo "  4. Uncomment the HTTPS server block in nginx.conf"
echo "  5. Run: docker compose restart nginx"
`
}
